//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace StdfReader {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stdf.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Arrays must be assignable. 的本地化字符串。
        /// </summary>
        internal static string ArraysMustBeAssignable {
            get {
                return ResourceManager.GetString("ArraysMustBeAssignable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 STDF only supports arrays up to {0} in length for field index {1} of {2}. 的本地化字符串。
        /// </summary>
        internal static string ArrayTooLong {
            get {
                return ResourceManager.GetString("ArrayTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nested iterations cannot be triggered inside RecordFilter implementations when caching is enabled. 的本地化字符串。
        /// </summary>
        internal static string CachingReEntrancy {
            get {
                return ResourceManager.GetString("CachingReEntrancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot write record without being able to infer the endianness of the output file. Use a StartOfStreamRecord or Far as the first record. 的本地化字符串。
        /// </summary>
        internal static string CannotInferEndianness {
            get {
                return ResourceManager.GetString("CannotInferEndianness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Ldc&lt;T&gt; does not support T is {0}. 的本地化字符串。
        /// </summary>
        internal static string CodeGen_UnsupportedGenericLdc {
            get {
                return ResourceManager.GetString("CodeGen_UnsupportedGenericLdc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} is not assignable from StdfRecord. 的本地化字符串。
        /// </summary>
        internal static string ConverterTargetNotStdfRecord {
            get {
                return ResourceManager.GetString("ConverterTargetNotStdfRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} bytes of corrupt data found at offset {1}. 的本地化字符串。
        /// </summary>
        internal static string CorruptDataMessage {
            get {
                return ResourceManager.GetString("CorruptDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The directory does not exist ({0}). 的本地化字符串。
        /// </summary>
        internal static string DirectoryNotFound {
            get {
                return ResourceManager.GetString("DirectoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Expected {0} more bytes while trying to read {1}. 的本地化字符串。
        /// </summary>
        internal static string EndOfStreamException {
            get {
                return ResourceManager.GetString("EndOfStreamException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The stream of records ended prematurely. The last record consumed must be an EndOfStreamRecord. 的本地化字符串。
        /// </summary>
        internal static string EndWithoutEOS {
            get {
                return ResourceManager.GetString("EndWithoutEOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End of Stream encountered while reading record header. 的本地化字符串。
        /// </summary>
        internal static string EOFInHeader {
            get {
                return ResourceManager.GetString("EOFInHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End of Stream encountered while reading record contents. 的本地化字符串。
        /// </summary>
        internal static string EOFInRecordContent {
            get {
                return ResourceManager.GetString("EOFInRecordContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 End of Stream encountered while in seek mode. 的本地化字符串。
        /// </summary>
        internal static string EOFInSeekMode {
            get {
                return ResourceManager.GetString("EOFInSeekMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You cannot modify the filters after records have been read. 的本地化字符串。
        /// </summary>
        internal static string ErrorFiltersLocked {
            get {
                return ResourceManager.GetString("ErrorFiltersLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The FAR record length was not reported as 2. 的本地化字符串。
        /// </summary>
        internal static string FarLengthError {
            get {
                return ResourceManager.GetString("FarLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The FAR could not be fully read. 的本地化字符串。
        /// </summary>
        internal static string FarReadError {
            get {
                return ResourceManager.GetString("FarReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The FAR record sub-type was not reported as 10. 的本地化字符串。
        /// </summary>
        internal static string FarRecordSubTypeError {
            get {
                return ResourceManager.GetString("FarRecordSubTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The FAR record type was not reported as 0. 的本地化字符串。
        /// </summary>
        internal static string FarRecordTypeError {
            get {
                return ResourceManager.GetString("FarRecordTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Fixed-length string layouts must provide a missing value. 的本地化字符串。
        /// </summary>
        internal static string FixedLengthStringMustHaveDefault {
            get {
                return ResourceManager.GetString("FixedLengthStringMustHaveDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 V4 sequence rules prohibit {0} int the state &quot;{1}&quot;. 的本地化字符串。
        /// </summary>
        internal static string InitialSequenceError {
            get {
                return ResourceManager.GetString("InitialSequenceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The data type code {0} is not defined in the STDF spec. 的本地化字符串。
        /// </summary>
        internal static string InvalidGdrDataTypeCode {
            get {
                return ResourceManager.GetString("InvalidGdrDataTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The unknown record type does not match the type of the converter. 的本地化字符串。
        /// </summary>
        internal static string InvalidRecordConverstionDefault {
            get {
                return ResourceManager.GetString("InvalidRecordConverstionDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can only save the dynamic assembly if debug is turned on and code has been generated. 的本地化字符串。
        /// </summary>
        internal static string InvalidSaveAssembly {
            get {
                return ResourceManager.GetString("InvalidSaveAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FieldIndex must be greater than or equal to zero. 的本地化字符串。
        /// </summary>
        internal static string NegativeFieldIndex {
            get {
                return ResourceManager.GetString("NegativeFieldIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Offset must be &gt;= 0. 的本地化字符串。
        /// </summary>
        internal static string NegativeOffset {
            get {
                return ResourceManager.GetString("NegativeOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 BitArray fields do not support array layout attributes. 的本地化字符串。
        /// </summary>
        internal static string NoBitArrayArrays {
            get {
                return ResourceManager.GetString("NoBitArrayArrays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Silverlight doesn&apos;t support debug mode. 的本地化字符串。
        /// </summary>
        internal static string NoDebugInSilverlight {
            get {
                return ResourceManager.GetString("NoDebugInSilverlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The stdf field indexes for type {0} are not consecutive and/or unique. 的本地化字符串。
        /// </summary>
        internal static string NonConsecutiveFieldIndexDefault {
            get {
                return ResourceManager.GetString("NonConsecutiveFieldIndexDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no contingency for writing &quot;NULL&quot; to field index {0} of {1}. 的本地化字符串。
        /// </summary>
        internal static string NonNullableField {
            get {
                return ResourceManager.GetString("NonNullableField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The type {0} has no registered unconverter. 的本地化字符串。
        /// </summary>
        internal static string NoRegisteredUnconverter {
            get {
                return ResourceManager.GetString("NoRegisteredUnconverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 String fields do not support array layout attributes. 的本地化字符串。
        /// </summary>
        internal static string NoStringArrays {
            get {
                return ResourceManager.GetString("NoStringArrays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The offset is to large to be stored in an StdfRecord. 的本地化字符串。
        /// </summary>
        internal static string OffsetTooLarge {
            get {
                return ResourceManager.GetString("OffsetTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 STDF only supports records up to 65535 bytes long. 的本地化字符串。
        /// </summary>
        internal static string RecordTooLong {
            get {
                return ResourceManager.GetString("RecordTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shared length arrays have differing lengths (length field index {0}). 的本地化字符串。
        /// </summary>
        internal static string SharedLengthViolation {
            get {
                return ResourceManager.GetString("SharedLengthViolation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot start a new file before ending the current one. 的本地化字符串。
        /// </summary>
        internal static string SOFBeforeEOF {
            get {
                return ResourceManager.GetString("SOFBeforeEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stdf strings must be at least 1 character long. 的本地化字符串。
        /// </summary>
        internal static string StdfStringLessThanOne {
            get {
                return ResourceManager.GetString("StdfStringLessThanOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 StringFieldLayoutAttribute can only define fields of type String. 的本地化字符串。
        /// </summary>
        internal static string StringFieldLayoutNonString {
            get {
                return ResourceManager.GetString("StringFieldLayoutNonString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 STDF only supports strings up to 255 characters long. 的本地化字符串。
        /// </summary>
        internal static string StringTooLong {
            get {
                return ResourceManager.GetString("StringTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TimeFieldLayoutAttribute can only define fields of type DateTime. 的本地化字符串。
        /// </summary>
        internal static string TimeFieldLayoutNonDateTime {
            get {
                return ResourceManager.GetString("TimeFieldLayoutNonDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Can&apos;t unconvert unknown records with the wrong Endianness. 的本地化字符串。
        /// </summary>
        internal static string UnconvertEndianMismatch {
            get {
                return ResourceManager.GetString("UnconvertEndianMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Array length fields must be either ushort or byte ({0} not supported). 的本地化字符串。
        /// </summary>
        internal static string UnsupportedArrayLengthType {
            get {
                return ResourceManager.GetString("UnsupportedArrayLengthType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Don&apos;t know how to write {0} to a GDR. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedGdrDataType {
            get {
                return ResourceManager.GetString("UnsupportedGdrDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No reader method for {0}. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedReaderType {
            get {
                return ResourceManager.GetString("UnsupportedReaderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This record converter factory does not support Stdf fields of type {0}. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedStdfFieldTypeMessage {
            get {
                return ResourceManager.GetString("UnsupportedStdfFieldTypeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No writer method for {0}. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedWriterType {
            get {
                return ResourceManager.GetString("UnsupportedWriterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 after ATR 的本地化字符串。
        /// </summary>
        internal static string V4ContentState_AfterAtr {
            get {
                return ResourceManager.GetString("V4ContentState_AfterAtr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 after FAR 的本地化字符串。
        /// </summary>
        internal static string V4ContentState_AfterFar {
            get {
                return ResourceManager.GetString("V4ContentState_AfterFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 after MIR 的本地化字符串。
        /// </summary>
        internal static string V4ContentState_AfterMir {
            get {
                return ResourceManager.GetString("V4ContentState_AfterMir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 after MRR 的本地化字符串。
        /// </summary>
        internal static string V4ContentState_AfterMrr {
            get {
                return ResourceManager.GetString("V4ContentState_AfterMrr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 after RDR 的本地化字符串。
        /// </summary>
        internal static string V4ContentState_AfterRdr {
            get {
                return ResourceManager.GetString("V4ContentState_AfterRdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 after SDR 的本地化字符串。
        /// </summary>
        internal static string V4ContentState_AfterSdr {
            get {
                return ResourceManager.GetString("V4ContentState_AfterSdr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 at end of file 的本地化字符串。
        /// </summary>
        internal static string V4ContentState_AtEOF {
            get {
                return ResourceManager.GetString("V4ContentState_AtEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 at start of file 的本地化字符串。
        /// </summary>
        internal static string V4ContentState_AtSOF {
            get {
                return ResourceManager.GetString("V4ContentState_AtSOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 before start of file 的本地化字符串。
        /// </summary>
        internal static string V4ContentState_BeforeSOF {
            get {
                return ResourceManager.GetString("V4ContentState_BeforeSOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 in the STDF body 的本地化字符串。
        /// </summary>
        internal static string V4ContentState_StdfBody {
            get {
                return ResourceManager.GetString("V4ContentState_StdfBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 in unknown state 的本地化字符串。
        /// </summary>
        internal static string V4ContentState_Unknown {
            get {
                return ResourceManager.GetString("V4ContentState_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Attempting to write outside of a StartOfStreamRecord/EndOfStreamRecord pair. 的本地化字符串。
        /// </summary>
        internal static string WriteOutsideSOSEOS {
            get {
                return ResourceManager.GetString("WriteOutsideSOSEOS", resourceCulture);
            }
        }
    }
}
